name: Deploying multiple files to EC2

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to Dev Server
      uses: appleboy/scp-action@master

      with:
        host: ${{ secrets.DEV_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "index.html,style.css,about.html,contact.html"
        target: "/home/ubuntu/"

    - name: Restart nginx on Dev Server ok
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo cp -r * /var/www/html/
          sudo systemctl restart nginx

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to Production Server
      uses: appleboy/scp-action@master

      with:
        host: ${{ secrets.PROD_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "index.html,style.css,about.html,contact.html"
        target: "/home/ubuntu/"

    - name: Restart nginx on Production Server
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.PROD_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo cp -r * /var/www/html/
          sudo systemctl restart nginx